name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'packages/frontend/**'
      - 'packages/backend/**'
  pull_request:
    branches: [main]
    paths:
      - 'packages/frontend/**'
      - 'packages/backend/**'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Run Frontend CI script
      run: pnpm --filter @monorepo-template/frontend run ci

    - name: Run Backend CI script
      run: pnpm --filter @monorepo-template/backend run ci
